version: 0.2
env:
  variables:
    S3_BUCKET: "angular-site-first"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id=E3MDQB9X1YF04E --paths '/*'
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
